"""Seed the exercise_catalog table with all exercises from Jeff Nippard's Essentials program."""

from sqlalchemy.orm import Session

from .models import ExerciseCatalog

# ---------------------------------------------------------------------------
# Complete catalog extracted from "Jeff Nippard - The Essentials 2.xlsx"
# (all 4 sheets: 2x, 3x, 4x, 5x Week).
#
# Typo variants in the spreadsheet (e.g. HAVK SQUAT, MACHINECRUNCH) are
# normalised here under their corrected canonical names. The raw names that
# appear in program_exercises.exercise_name_raw should be mapped to these
# canonical names elsewhere.
# ---------------------------------------------------------------------------

EXERCISE_CATALOG = [
    # ── CHEST ──────────────────────────────────────────────────────────────
    {
        "canonical_name": "FLAT DB PRESS (HEAVY)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "FLAT DB PRESS (GET OFF)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INCLINE DB PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INCLINE DB CHEST PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INCLINE DUMBBELL PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SLIGHT INCLINE DB PRESS (HEAVY)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SLIGHT INCLINE DB PRESS (BACK OFF)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INCLINE SMITH MACHINE PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "INCLINE MACHINE PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE CHEST PRESS (HEAVY)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE CHEST PRESS (BACK OFF)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE PRESS (BACK OFF)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SMITH MACHINE CHEST PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CABLE CHEST FLY",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE CHEST FLY",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "PEC DECK",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CABLE CHEST PRESS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "CABLE CHEST PRESS PUSHUPS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "WEIGHTED DIP",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
        "bodyweight_kind": "weighted_capable",
    },
    {
        "canonical_name": "WEIGHTED DIP (HEAVY)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
        "bodyweight_kind": "weighted_capable",
    },
    {
        "canonical_name": "WEIGHTED DIP (BACK OFF)",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
        "bodyweight_kind": "weighted_capable",
    },
    {
        "canonical_name": "DIP",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "DIPS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "BODYWEIGHT DIP",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "PUSHUPS",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CLOSE-GRIP PUSH UP",
        "muscle_group_primary": "chest",
        "muscle_groups_secondary": ["triceps", "shoulders"],
        "movement_pattern": "horizontal push",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── BACK ───────────────────────────────────────────────────────────────
    {
        "canonical_name": "2-GRIP LAT PULLDOWN",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LAT PULLDOWN",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "NEUTRAL GRIP LAT PULLDOWN",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "1-ARM HALF KNEELING LAT PULLDOWN",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "MACHINE PULLDOWN",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "T-BAR ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "barbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SEATED CABLE ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "HELMS DB ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "PENDLAY ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "barbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "MEADOWS ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "barbell",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SINGLE-ARM DB ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INCLINE CHEST-SUPPORTED DB ROW",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "horizontal pull",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "PULLUP",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "WEIGHTED PULLUP",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
        "bodyweight_kind": "weighted_capable",
    },
    {
        "canonical_name": "2-GRIP PULLUP",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "2-GRIP PULLUP (ASSISTED)",
        "muscle_group_primary": "back",
        "muscle_groups_secondary": ["biceps"],
        "movement_pattern": "vertical pull",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── SHOULDERS ──────────────────────────────────────────────────────────
    {
        "canonical_name": "DB LATERAL RAISE",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "STANDING DB LATERAL RAISE",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CABLE LATERAL RAISE",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": True,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE LATERAL RAISE",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SEATED DB SHOULDER PRESS",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["triceps"],
        "movement_pattern": "vertical push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "CABLE SHOULDER PRESS",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["triceps"],
        "movement_pattern": "vertical push",
        "equipment": "cable",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "STANDING DB ARNOLD PRESS",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["triceps"],
        "movement_pattern": "vertical push",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "REVERSE CABLE FLY",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["back"],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "REVERSE PEC DECK",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["back"],
        "movement_pattern": "isolation upper",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "BENT-OVER REVERSE DB FLYE",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["back"],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "ROPE FACEPULL",
        "muscle_group_primary": "shoulders",
        "muscle_groups_secondary": ["back"],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── QUADS ──────────────────────────────────────────────────────────────
    {
        "canonical_name": "HACK SQUAT (HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "HACK SQUAT (BACK OFF)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "CLOSE STANCE HACK SQUAT",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "MACHINE SQUAT (HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE SQUAT (BACK OFF)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SMITH MACHINE SQUAT (HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SMITH MACHINE SQUAT (BACK OFF)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "NARROW STANCE SMITH SQUAT",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "GOBLET SQUAT",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LEG PRESS (HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LEG PRESS (BACK OFF)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LEG PRESS",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        # Typo variant in spreadsheet (missing space)
        "canonical_name": "LEG PRESS(HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SINGLE-LEG LEG PRESS (HEAVY)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SINGLE-LEG LEG PRESS (BACK OFF)",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "squat",
        "equipment": "machine",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "LEG EXTENSION",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "DB BULGARIAN SPLIT SQUAT",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "lunge",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "DB WALKING LUNGE",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "lunge",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "BW WALKING LUNGES",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "lunge",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "beginner",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "WALKING LUNGES",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "lunge",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "beginner",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "DB STEP UP",
        "muscle_group_primary": "quads",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "lunge",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    # ── HAMSTRINGS ─────────────────────────────────────────────────────────
    {
        "canonical_name": "ROMANIAN DEADLIFT",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": ["glutes", "back"],
        "movement_pattern": "hip hinge",
        "equipment": "barbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "DB ROMANIAN DEADLIFT",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": ["glutes", "back"],
        "movement_pattern": "hip hinge",
        "equipment": "dumbbell",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "SEATED HAMSTRING CURL",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SEATED LEG CURL",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LYING LEG CURL",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "NORDIC HAM CURL",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "advanced",
    },
    {
        "canonical_name": "GLUTE-HAM RAISE",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": ["glutes"],
        "movement_pattern": "hip hinge",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "advanced",
    },
    {
        "canonical_name": "45-DEGREE BACK EXTENSION",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": ["glutes", "back"],
        "movement_pattern": "hip hinge",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "45-DEGREE HYPEREXTENSION",
        "muscle_group_primary": "hamstrings",
        "muscle_groups_secondary": ["glutes", "back"],
        "movement_pattern": "hip hinge",
        "equipment": "bodyweight",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── BICEPS ─────────────────────────────────────────────────────────────
    {
        "canonical_name": "DB BICEP CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "EZ BAR CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CABLE EZ CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SPIDER CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "DB SPIDER CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "MACHINE BICEP CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "BAYESIAN CABLE CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": True,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "INVERSE ZOTTMAN CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": ["forearms"],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "EZ BAR PREACHER CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "DB INCLINE CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "REVERSE GRIP EZ BAR CURL",
        "muscle_group_primary": "biceps",
        "muscle_groups_secondary": ["forearms"],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    # ── TRICEPS ────────────────────────────────────────────────────────────
    {
        "canonical_name": "DB SKULL CRUSHER",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "EZ BAR SKULL CRUSHER",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "OVERHEAD CABLE TRICEPS EXTENSIONS",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "CABLE TRICEPS KICKBACK",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": True,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "DB TRICEPS KICKBACK",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": True,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "TRICEPS PRESSDOWN",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        # Typo variant in spreadsheet (missing S)
        "canonical_name": "TRICEP PRESSDOWN",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "SMITH MACHINE JM PRESS",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": ["chest"],
        "movement_pattern": "isolation upper",
        "equipment": "smith machine",
        "is_compound": True,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "DB FRENCH PRESS",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "dumbbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "EZ BAR FRENCH PRESS",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "barbell",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
    },
    {
        "canonical_name": "MACHINE TRICEPS EXTENSION",
        "muscle_group_primary": "triceps",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation upper",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── CALVES ─────────────────────────────────────────────────────────────
    {
        "canonical_name": "SEATED CALF RAISE",
        "muscle_group_primary": "calves",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "STANDING CALF RAISE",
        "muscle_group_primary": "calves",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "LEG PRESS TOE PRESS",
        "muscle_group_primary": "calves",
        "muscle_groups_secondary": [],
        "movement_pattern": "isolation lower",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    # ── ABS / CORE ─────────────────────────────────────────────────────────
    {
        "canonical_name": "CABLE CRUNCH",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "cable",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "MACHINE CRUNCH",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "machine",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
    },
    {
        "canonical_name": "HANGING LEG RAISE",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "LEG RAISES",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "ROMAN CHAIR CRUNCH",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "intermediate",
        "bodyweight_kind": "pure",
    },
    {
        "canonical_name": "PLATE-WEIGHTED CRUNCH",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
        "bodyweight_kind": "weighted_capable",
    },
    {
        "canonical_name": "TWO-ARMS TWO-LEGS DEAD BUG",
        "muscle_group_primary": "abs",
        "muscle_groups_secondary": [],
        "movement_pattern": "core",
        "equipment": "bodyweight",
        "is_compound": False,
        "is_unilateral": False,
        "difficulty_level": "beginner",
        "bodyweight_kind": "pure",
    },
]


def seed_exercise_catalog(db_session: Session) -> int:
    """Populate the exercise_catalog table with all Essentials program exercises.

    Checks if exercises already exist to avoid duplicates on re-run.

    Args:
        db_session: An active SQLAlchemy session.

    Returns:
        Number of exercises inserted.
    """
    existing_names = {
        row.canonical_name
        for row in db_session.query(ExerciseCatalog.canonical_name).all()
    }

    to_insert = [
        ExerciseCatalog(**entry)
        for entry in EXERCISE_CATALOG
        if entry["canonical_name"] not in existing_names
    ]

    if to_insert:
        db_session.add_all(to_insert)
        db_session.commit()

    inserted_count = len(to_insert)
    total_count = len(existing_names) + inserted_count
    print(f"Exercise catalog: {inserted_count} new exercises inserted ({total_count} total in catalog)")
    return inserted_count


def backfill_catalog_bodyweight_kind(db):
    """Update existing ExerciseCatalog rows with the bodyweight_kind value
    from the EXERCISE_CATALOG seed list. Idempotent — only updates rows
    where the DB value differs from the seed value (so it can be called on
    every startup safely).
    """
    from .models import ExerciseCatalog
    seed_by_name = {
        entry["canonical_name"]: entry.get("bodyweight_kind")
        for entry in EXERCISE_CATALOG
    }
    for cat in db.query(ExerciseCatalog).all():
        wanted = seed_by_name.get(cat.canonical_name)
        if cat.bodyweight_kind != wanted:
            cat.bodyweight_kind = wanted
    db.commit()


if __name__ == "__main__":
    from .database import SessionLocal

    db = SessionLocal()
    try:
        seed_exercise_catalog(db)
    finally:
        db.close()
